name: Deploy Bot

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.3
      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-east-1
      - name: Deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: wikimedia-bot-cfn-deploy
          template: ./aws-infra.yaml
          no-fail-on-empty-changeset: "1"

